# Generated by Django 4.1.7 on 2023-03-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drinks', '0002_drink_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='uid',
        ),
    ]
